/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filemanager;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MerryGoRound
 */
public class JCampos extends javax.swing.JFrame {

    ArrayList <fieldStructure> listaCampos = new ArrayList <fieldStructure>(); 
    public JCampos() {
        initComponents();
        this.setLocationRelativeTo(this);
        archivosDisponibles();
        this.listaCampos.add(new fieldStructure(true,false,"ID",
        "Numero"));
        camposDisponibles();
    }
    
     public void archivosDisponibles(){
        File path = new File("tables");
        String[] listaArchivos = path.list();
        this.cmbArchivosDisponibles.removeAllItems();
        for (String listaArchivo : listaArchivos) {
            this.cmbArchivosDisponibles.addItem(listaArchivo);
        }  
    }
     
    public void camposDisponibles(){
        cmbCamposDisponibles.removeAllItems();
        listaCampos.forEach((listaCampo) -> {
            this.cmbCamposDisponibles.addItem(listaCampo.getFieldName());
        });
    }
    public int indexCampo(String campo){
        for (int i = 0; i <10; i++) {
            
            if (campo.equals(listaCampos.get(i).getFieldName())){
                return i;
            }
        }
        return -1;            
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCrearCampo = new javax.swing.JButton();
        btnModificarCampo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbArchivosDisponibles = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbCamposDisponibles = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNombresCampos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbLlaveSecundaria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbTipoDato = new javax.swing.JComboBox<>();
        btnCrearMeta = new javax.swing.JButton();
        btnGuardarCampo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CAMPOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Crear");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Eliminar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Modificar");

        btnCrearCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filemanager/Icons/crearCamp.png"))); // NOI18N
        btnCrearCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCampoActionPerformed(evt);
            }
        });

        btnModificarCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filemanager/Icons/modificarCampo.png"))); // NOI18N
        btnModificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCampoActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filemanager/Icons/borrar formato.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Campos Disponibles:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Archivos Disponibles: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nombre Campo:");

        txtNombresCampos.setEnabled(false);
        txtNombresCampos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresCamposFocusLost(evt);
            }
        });
        txtNombresCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresCamposActionPerformed(evt);
            }
        });
        txtNombresCampos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombresCamposKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Llave secundaria:");

        cmbLlaveSecundaria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbLlaveSecundaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cmbLlaveSecundaria.setEnabled(false);
        cmbLlaveSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLlaveSecundariaActionPerformed(evt);
            }
        });
        cmbLlaveSecundaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbLlaveSecundariaKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de Dato:");

        cmbTipoDato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbTipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Texto", "Numero", "Moneda", "Fecha", "Telefono", "Hora" }));
        cmbTipoDato.setEnabled(false);
        cmbTipoDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDatoActionPerformed(evt);
            }
        });

        btnCrearMeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearMeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filemanager/Icons/crear meta.png"))); // NOI18N
        btnCrearMeta.setEnabled(false);
        btnCrearMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMetaActionPerformed(evt);
            }
        });

        btnGuardarCampo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardarCampo.setText("Guardar Campo");
        btnGuardarCampo.setEnabled(false);
        btnGuardarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCampoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Guardar Campos ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel4))
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel1)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnModificarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuardarCampo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbArchivosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(jLabel5))
                                                    .addComponent(cmbCamposDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnCrearMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel10))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGap(26, 26, 26)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNombresCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmbLlaveSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(51, 51, 51)
                                                    .addComponent(cmbTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 29, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnCrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombresCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbLlaveSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbArchivosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCamposDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrearMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCampoActionPerformed
        if(cmbCamposDisponibles.getSelectedItem().equals("ID")){
            JOptionPane.showMessageDialog(null,"el Campo: " + cmbCamposDisponibles.getSelectedItem()+
                    " no puede ser Modificado");            
        }else{            
            this.txtNombresCampos.setEnabled(true);
            this.btnModificarCampo.setEnabled(false);
            this.btnBorrar.setEnabled(false);
            this.btnCrearCampo.setEnabled(false);
            
            //agregar valores del campo seleccionado al Campo
            txtNombresCampos.setText(listaCampos.get(cmbCamposDisponibles.getSelectedIndex()).getFieldName());
            listaCampos.remove(cmbCamposDisponibles.getSelectedIndex());
            camposDisponibles();
            txtNombresCampos.setEnabled(true);
            cmbLlaveSecundaria.setEnabled(true);
            cmbTipoDato.setEnabled(true);
            txtNombresCampos.requestFocus();
            
        }
        
        
    }//GEN-LAST:event_btnModificarCampoActionPerformed

    private void btnCrearMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMetaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Esta Seguro que quiere Guardar "
                + "los Campos en el archivo Seleccionado?","ELIMINAR ARCHIVO!!!!",
                JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_btnCrearMetaActionPerformed

    private void btnGuardarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCampoActionPerformed
        boolean secondkey=false;
        String name=this.txtNombresCampos.getText();
        if (cmbLlaveSecundaria.getSelectedItem().equals("Si")) {
            secondkey=true;
        }
        String dataType=(String) cmbTipoDato.getSelectedItem();
        listaCampos.add(new fieldStructure(false, secondkey, name, dataType));
        camposDisponibles();
        this.txtNombresCampos.setText("");
        btnBorrar.setEnabled(true);
        btnCrearCampo.setEnabled(true);
        btnModificarCampo.setEnabled(true);
        cmbLlaveSecundaria.setEnabled(false);
        cmbTipoDato.setEnabled(false);
        txtNombresCampos.setEnabled(false);
        btnGuardarCampo.setEnabled(false);
        btnCrearCampo.requestFocus();
        btnCrearMeta.setEnabled(true);
        
        
    }//GEN-LAST:event_btnGuardarCampoActionPerformed

    private void btnCrearCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCampoActionPerformed
        this.txtNombresCampos.setEnabled(true);
        this.txtNombresCampos.requestFocus();
        this.btnModificarCampo.setEnabled(false);
        this.btnBorrar.setEnabled(false);
        this.btnCrearCampo.setEnabled(false);
        btnCrearMeta.setEnabled(false);
    }//GEN-LAST:event_btnCrearCampoActionPerformed

    private void txtNombresCamposFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresCamposFocusLost
        if(this.txtNombresCampos.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Este campo no puede estar vacio");
            this.txtNombresCampos.requestFocus();
        } else if (fieldnameExists(this.txtNombresCampos.getText())) {
            JOptionPane.showMessageDialog(null,"Este campo ya existe");
            this.txtNombresCampos.requestFocus();
            this.txtNombresCampos.setText("");
        }else{
            this.cmbLlaveSecundaria.requestFocus();
            
        } 
        
    }//GEN-LAST:event_txtNombresCamposFocusLost

    private void txtNombresCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresCamposActionPerformed

    private void cmbLlaveSecundariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbLlaveSecundariaKeyPressed
        
    }//GEN-LAST:event_cmbLlaveSecundariaKeyPressed

    private void cmbLlaveSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLlaveSecundariaActionPerformed
        cmbTipoDato.setEnabled(true);
        cmbTipoDato.requestFocus();
    }//GEN-LAST:event_cmbLlaveSecundariaActionPerformed

    private void txtNombresCamposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresCamposKeyPressed
        cmbLlaveSecundaria.setEnabled(txtNombresCampos.getText().length()!=0);
    }//GEN-LAST:event_txtNombresCamposKeyPressed

    private void cmbTipoDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDatoActionPerformed
        btnGuardarCampo.setEnabled(true);
        btnGuardarCampo.requestFocus();
    }//GEN-LAST:event_cmbTipoDatoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        if(cmbCamposDisponibles.getSelectedItem().equals("ID")){
            JOptionPane.showMessageDialog(null,"el Campo: " + cmbCamposDisponibles.getSelectedItem()+
                    " no puede ser Eliminado");            
        }else{
            int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que quiere eliminar "
                + "el Campo seleccionado?","ELIMINAR ARCHIVO!!!!",
                JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                listaCampos.remove(cmbCamposDisponibles.getSelectedIndex());
                JOptionPane.showMessageDialog(null, "Campo Eliminado con exito!");
                camposDisponibles();
            }                
        }
        if(cmbCamposDisponibles.getItemCount()==1){
            btnCrearMeta.setEnabled(false);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed
    
    public boolean fieldnameExists(String name){
        for (int i = 0; i < listaCampos.size(); i++) {
            if (listaCampos.get(i).getFieldName().equalsIgnoreCase(name)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCampos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrearCampo;
    private javax.swing.JButton btnCrearMeta;
    private javax.swing.JButton btnGuardarCampo;
    private javax.swing.JButton btnModificarCampo;
    private javax.swing.JComboBox<String> cmbArchivosDisponibles;
    private javax.swing.JComboBox<String> cmbCamposDisponibles;
    private javax.swing.JComboBox<String> cmbLlaveSecundaria;
    private javax.swing.JComboBox<String> cmbTipoDato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtNombresCampos;
    // End of variables declaration//GEN-END:variables
}
